apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /Users/user/development/storage/mongo
  claimRef:
    name: mongo-data-pvc
    namespace: default
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual